[package]
name = "severian-lowering"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
severian-artifact = { path = "../../artifact" }
severian-lir = { path = "../lir" }
severian-mir = { path = "../mir" }
severian-target = { path = "../../target" }
severian-universal = { path = "../../universal" }

[lib]
path = "src/lib.rs"
