[package]
name = "severian-semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
severian-ast = { version = "0.1.0", path = "../ast" }
severian-hir = { version = "0.1.0", path = "../hir" }
severian-package = { version = "0.1.0", path = "../package" }

[dev-dependencies]
severian-lexer = { version = "0.1.0", path = "../lexer" }
severian-parser = { version = "0.1.0", path = "../parser" }
