[package]
name = "automatic-model-fusion-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "automatic-model-fusion-example"
path = "main.sev"

[dependencies]
matrix = { path = "../../../library/matrix", version = "0.1.0" }
tensor = { path = "../../../library/tensor", version = "0.1.0" }
model = { path = "../../../library/model", version = "0.1.0" }
