[workspace]
members = [
    # Boundaries
    "compiler/boundaries/abi",
    "compiler/boundaries/backend",
    "compiler/boundaries/driver",
    "compiler/boundaries/interface",

    # Cross-cutting
    "compiler/diagnostics",

    # Frontend
    "compiler/frontend/ast",
    "compiler/frontend/hir",
    "compiler/frontend/lexer",
    "compiler/frontend/ownership",
    "compiler/frontend/parser",
    "compiler/frontend/semantic",
    "compiler/frontend/source",

    # Transforms
    "compiler/transforms/lowering",
    "compiler/transforms/mir",
    "compiler/transforms/mlir",
]
resolver = "2"

[workspace.package]
edition = "2021"
license-file = "LICENSE.md"
repository = "https://github.com/tlplayer/Severian"
version = "0.1.0"
