[workspace]
members = [
    "compiler/abi",
    "compiler/ast",
    "compiler/backend",
    "compiler/build",
    "compiler/coverage",
    "compiler/diagnostics",
    "compiler/dtype",
    "compiler/driver",
    "compiler/hir",
    "compiler/lexer",
    "compiler/lowering",
    "compiler/mir",
    "compiler/mlir",
    "compiler/model-ir",
    "compiler/ownership",
    "compiler/package",
    "compiler/parser",
    "compiler/passes",
    "compiler/platform",
    "compiler/runtime",
    "compiler/semantic",
    "compiler/source",
]
resolver = "2"

[workspace.package]
edition = "2021"
license-file = "LICENSE.md"
repository = "https://github.com/tlplayer/Severian"
version = "0.1.0"
