//! C ABI used by native Severian host programs to execute compiled tensor
//! regions. Kernel StableHLO is generated by the Severian frontend/lowerer and
//! embedded by the native bridge; this runtime only owns PJRT state and buffers.

use crate::{
    Buffer, CompileOptions, Device, HostBuffer, LoadedExecutable, PjrtClient, PjrtPlugin,
    StableHloModule, XlaClient,
};
use crate::pjrt::{ElementType, Shape};
use std::{
    collections::HashMap,
    ffi::c_void,
    slice,
    sync::{Mutex, OnceLock},
};

#[repr(C)]
struct MappedBf16Tensor {
    rank: i64,
    shape: *const i64,
    elements: i64,
    data: *const u16,
}

struct RuntimeState {
    client: XlaClient,
    device: Device,
    executables: HashMap<u64, LoadedExecutable>,
    buffers: HashMap<usize, Buffer>,
}

static STATE: OnceLock<Mutex<Option<RuntimeState>>> = OnceLock::new();

fn fail(message: impl std::fmt::Display) -> ! {
    eprintln!("Severian XLA runtime error: {message}");
    std::process::abort()
}

fn state() -> std::sync::MutexGuard<'static, Option<RuntimeState>> {
    let mut guard = STATE
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap_or_else(|error| error.into_inner());
    if guard.is_none() {
        let plugin = PjrtPlugin::load_rocm().unwrap_or_else(|error| fail(error));
        let pjrt = PjrtClient::new(plugin).unwrap_or_else(|error| fail(error));
        let device = pjrt.amd_gpu_device().unwrap_or_else(|error| fail(error));
        guard.replace(RuntimeState {
            client: XlaClient::new(pjrt),
            device,
            executables: HashMap::new(),
            buffers: HashMap::new(),
        });
    }
    guard
}

fn new_handle() -> *mut c_void {
    Box::into_raw(Box::new(0_u8)).cast()
}

unsafe fn upload_mapped_bf16(runtime: &mut RuntimeState, pointer: *mut c_void) {
    let tensor = &*pointer.cast::<MappedBf16Tensor>();
    if tensor.rank <= 0 || tensor.elements < 0 || tensor.shape.is_null() || tensor.data.is_null() {
        fail("invalid mapped BF16 tensor passed to XLA");
    }
    let dimensions = slice::from_raw_parts(tensor.shape, tensor.rank as usize).to_vec();
    let byte_len = (tensor.elements as usize)
        .checked_mul(2)
        .unwrap_or_else(|| fail("mapped BF16 tensor byte size overflow"));
    let bytes = slice::from_raw_parts(tensor.data.cast::<u8>(), byte_len).to_vec();
    let host = HostBuffer::new(Shape::new(ElementType::BF16, dimensions), bytes)
        .unwrap_or_else(|error| fail(error));
    let buffer = runtime
        .client
        .upload_to(host, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    runtime.buffers.insert(pointer as usize, buffer);
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_i64_token(value: i64) -> *mut c_void {
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    let host = HostBuffer::from_i64([1, 1], &[value]).unwrap_or_else(|error| fail(error));
    let buffer = runtime
        .client
        .upload_to(host, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    let handle = new_handle();
    runtime.buffers.insert(handle as usize, buffer);
    handle
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_execute(
    function: u64,
    module_data: *const u8,
    module_len: usize,
    arguments: *const *mut c_void,
    argument_count: usize,
) -> *mut c_void {
    if module_data.is_null() || arguments.is_null() {
        fail("null kernel module or argument list");
    }
    let module = std::str::from_utf8(slice::from_raw_parts(module_data, module_len))
        .unwrap_or_else(|error| fail(error));
    let pointers = slice::from_raw_parts(arguments, argument_count);
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    for &pointer in pointers {
        if pointer.is_null() {
            fail("null tensor argument");
        }
        if !runtime.buffers.contains_key(&(pointer as usize)) {
            upload_mapped_bf16(runtime, pointer);
        }
    }
    if !runtime.executables.contains_key(&function) {
        let executable = runtime
            .client
            .compile(
                &StableHloModule::from_text(module),
                &CompileOptions::default(),
            )
            .unwrap_or_else(|error| fail(error));
        runtime.executables.insert(function, executable);
    }
    let executable = runtime.executables.get(&function).unwrap();
    let inputs = pointers
        .iter()
        .map(|pointer| runtime.buffers.get(&(*pointer as usize)).unwrap())
        .collect::<Vec<_>>();
    let mut outputs = executable
        .execute(&inputs, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    if outputs.len() != 1 {
        fail(format!("tensor region returned {} buffers; expected one", outputs.len()));
    }
    let handle = new_handle();
    runtime.buffers.insert(handle as usize, outputs.remove(0));
    handle
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_argmax_bf16(tensor: *mut c_void) -> i64 {
    let guard = state();
    let runtime = guard.as_ref().unwrap();
    let buffer = runtime
        .buffers
        .get(&(tensor as usize))
        .unwrap_or_else(|| fail("argmax requires an XLA output tensor"));
    let bytes = buffer.to_host_bytes().unwrap_or_else(|error| fail(error));
    bytes
        .chunks_exact(2)
        .enumerate()
        .map(|(index, bytes)| {
            let bits = u16::from_ne_bytes([bytes[0], bytes[1]]);
            (index, f32::from_bits(u32::from(bits) << 16))
        })
        .max_by(|left, right| left.1.total_cmp(&right.1))
        .map(|(index, _)| index as i64)
        .unwrap_or_else(|| fail("argmax received an empty tensor"))
}
