//! C ABI used by native Severian host programs to execute compiled tensor
//! regions. Kernel StableHLO is generated by the Severian frontend/lowerer and
//! embedded by the native bridge; this runtime only owns PJRT state and buffers.

use crate::pjrt::{ElementType, Shape};
use crate::{
    Buffer, CompileOptions, Device, HostBuffer, LoadedExecutable, PjrtClient, PjrtPlugin,
    StableHloModule, XlaClient,
};
use std::{
    collections::HashMap,
    ffi::c_void,
    slice,
    sync::{Mutex, OnceLock},
};

#[repr(C)]
struct MappedTensor {
    magic: u64,
    dtype: i32,
    element_bytes: i32,
    rank: i64,
    shape: *const i64,
    elements: i64,
    data: *const c_void,
}

const MAPPED_TENSOR_MAGIC: u64 = 0x5345_5654_454E_534F;

struct RuntimeState {
    client: XlaClient,
    device: Device,
    executables: HashMap<u64, LoadedExecutable>,
    buffers: HashMap<usize, Buffer>,
}

static STATE: OnceLock<Mutex<Option<RuntimeState>>> = OnceLock::new();
fn fail(message: impl std::fmt::Display) -> ! {
    eprintln!("Severian XLA runtime error: {message}");
    std::process::abort()
}

fn state() -> std::sync::MutexGuard<'static, Option<RuntimeState>> {
    let mut guard = STATE
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap_or_else(|error| error.into_inner());
    if guard.is_none() {
        let plugin = PjrtPlugin::load_rocm().unwrap_or_else(|error| fail(error));
        let pjrt = PjrtClient::new(plugin).unwrap_or_else(|error| fail(error));
        let device = pjrt.amd_gpu_device().unwrap_or_else(|error| fail(error));
        guard.replace(RuntimeState {
            client: XlaClient::new(pjrt),
            device,
            executables: HashMap::new(),
            buffers: HashMap::new(),
        });
    }
    guard
}

fn new_handle() -> *mut c_void {
    Box::into_raw(Box::new(0_u8)).cast()
}

unsafe fn upload_mapped_tensor(runtime: &mut RuntimeState, pointer: *mut c_void) {
    let tensor = &*pointer.cast::<MappedTensor>();
    if tensor.magic != MAPPED_TENSOR_MAGIC
        || tensor.rank <= 0
        || tensor.elements < 0
        || tensor.shape.is_null()
        || tensor.data.is_null()
    {
        fail("invalid mapped tensor passed to XLA");
    }
    let element = match tensor.dtype {
        0 => ElementType::Bool,
        1 => ElementType::I8,
        2 => ElementType::I16,
        3 => ElementType::I32,
        4 => ElementType::I64,
        5 => ElementType::U8,
        6 => ElementType::U16,
        7 => ElementType::U32,
        8 => ElementType::U64,
        9 => ElementType::F8E4M3FN,
        10 => ElementType::F8E5M2,
        11 => ElementType::F16,
        12 => ElementType::BF16,
        13 => ElementType::F32,
        14 => ElementType::F64,
        15 => ElementType::C64,
        16 => ElementType::C128,
        other => fail(format!("mapped tensor has unknown dtype tag {other}")),
    };
    if tensor.element_bytes as usize != element.byte_width() {
        fail("mapped tensor dtype and element width disagree");
    }
    let dimensions = slice::from_raw_parts(tensor.shape, tensor.rank as usize).to_vec();
    let byte_len = (tensor.elements as usize)
        .checked_mul(element.byte_width())
        .unwrap_or_else(|| fail("mapped tensor byte size overflow"));
    let bytes = slice::from_raw_parts(tensor.data.cast::<u8>(), byte_len).to_vec();
    let host =
        HostBuffer::new(Shape::new(element, dimensions), bytes).unwrap_or_else(|error| fail(error));
    let buffer = runtime
        .client
        .upload_to(host, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    runtime.buffers.insert(pointer as usize, buffer);
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_release(tensor: *mut c_void) {
    if tensor.is_null() {
        return;
    }
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    if runtime.buffers.remove(&(tensor as usize)).is_some() {
        drop(Box::from_raw(tensor.cast::<u8>()));
    }
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_execute(
    function: u64,
    module_data: *const u8,
    module_len: usize,
    arguments: *const *mut c_void,
    argument_count: usize,
) -> *mut c_void {
    if module_data.is_null() || arguments.is_null() {
        fail("null kernel module or argument list");
    }
    let module = std::str::from_utf8(slice::from_raw_parts(module_data, module_len))
        .unwrap_or_else(|error| fail(error));
    let pointers = slice::from_raw_parts(arguments, argument_count);
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    for &pointer in pointers {
        if pointer.is_null() {
            fail("null tensor argument");
        }
        if !runtime.buffers.contains_key(&(pointer as usize)) {
            upload_mapped_tensor(runtime, pointer);
        }
    }
    if !runtime.executables.contains_key(&function) {
        let executable = runtime
            .client
            .compile(
                &StableHloModule::from_text(module),
                &CompileOptions::default(),
            )
            .unwrap_or_else(|error| fail(error));
        runtime.executables.insert(function, executable);
    }
    let executable = runtime.executables.get(&function).unwrap();
    let inputs = pointers
        .iter()
        .map(|pointer| runtime.buffers.get(&(*pointer as usize)).unwrap())
        .collect::<Vec<_>>();
    let mut outputs = executable
        .execute(&inputs, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    if outputs.len() != 1 {
        fail(format!(
            "tensor region returned {} buffers; expected one",
            outputs.len()
        ));
    }
    let handle = new_handle();
    runtime.buffers.insert(handle as usize, outputs.remove(0));
    handle
}
