//! C ABI used by native Severian host programs to execute compiled tensor
//! regions. Kernel StableHLO is generated by the Severian frontend/lowerer and
//! embedded by the native bridge; this runtime only owns PJRT state and buffers.

use crate::pjrt::{ElementType, Shape};
use crate::{
    Buffer, CompileOptions, Device, HostBuffer, LoadedExecutable, PjrtClient, PjrtPlugin,
    StableHloModule, XlaClient,
};
use std::{
    collections::HashMap,
    ffi::c_void,
    slice,
    sync::{Mutex, OnceLock},
};

unsafe extern "C" {
    fn __sev_collection_size(collection: *mut c_void) -> i64;
    fn __sev_collection_get(collection: *mut c_void, index: i64) -> *mut c_void;
    fn __sev_unbox_i64(value: *mut c_void) -> i64;
}

#[repr(C)]
struct MappedTensor {
    magic: u64,
    dtype: i32,
    element_bytes: i32,
    rank: i64,
    shape: *const i64,
    elements: i64,
    data: *const c_void,
}

const MAPPED_TENSOR_MAGIC: u64 = 0x5345_5654_454E_534F;

struct RuntimeState {
    client: XlaClient,
    device: Device,
    executables: HashMap<u64, LoadedExecutable>,
    buffers: HashMap<usize, Buffer>,
}

static STATE: OnceLock<Mutex<Option<RuntimeState>>> = OnceLock::new();
const QWEN_PREFILL_CAPACITY: usize = 32;
const QWEN_SERVING_PREFILL_TOKENS: usize = 256;
const QWEN_SERVING_CACHE_TOKENS: usize = 288;
const QWEN_KV_HEADS: usize = 2;
const QWEN_HEAD_DIMENSION: usize = 128;

fn fail(message: impl std::fmt::Display) -> ! {
    eprintln!("Severian XLA runtime error: {message}");
    std::process::abort()
}

fn state() -> std::sync::MutexGuard<'static, Option<RuntimeState>> {
    let mut guard = STATE
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap_or_else(|error| error.into_inner());
    if guard.is_none() {
        let plugin = PjrtPlugin::load_rocm().unwrap_or_else(|error| fail(error));
        let pjrt = PjrtClient::new(plugin).unwrap_or_else(|error| fail(error));
        let device = pjrt.amd_gpu_device().unwrap_or_else(|error| fail(error));
        guard.replace(RuntimeState {
            client: XlaClient::new(pjrt),
            device,
            executables: HashMap::new(),
            buffers: HashMap::new(),
        });
    }
    guard
}

fn new_handle() -> *mut c_void {
    Box::into_raw(Box::new(0_u8)).cast()
}

fn upload_host(runtime: &mut RuntimeState, host: HostBuffer) -> *mut c_void {
    let buffer = runtime
        .client
        .upload_to(host, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    let handle = new_handle();
    runtime.buffers.insert(handle as usize, buffer);
    handle
}

unsafe fn upload_mapped_tensor(runtime: &mut RuntimeState, pointer: *mut c_void) {
    let tensor = &*pointer.cast::<MappedTensor>();
    if tensor.magic != MAPPED_TENSOR_MAGIC
        || tensor.rank <= 0
        || tensor.elements < 0
        || tensor.shape.is_null()
        || tensor.data.is_null()
    {
        fail("invalid mapped tensor passed to XLA");
    }
    let element = match tensor.dtype {
        0 => ElementType::Bool,
        1 => ElementType::I8,
        2 => ElementType::I16,
        3 => ElementType::I32,
        4 => ElementType::I64,
        5 => ElementType::U8,
        6 => ElementType::U16,
        7 => ElementType::U32,
        8 => ElementType::U64,
        9 => ElementType::F8E4M3FN,
        10 => ElementType::F8E5M2,
        11 => ElementType::F16,
        12 => ElementType::BF16,
        13 => ElementType::F32,
        14 => ElementType::F64,
        15 => ElementType::C64,
        16 => ElementType::C128,
        other => fail(format!("mapped tensor has unknown dtype tag {other}")),
    };
    if tensor.element_bytes as usize != element.byte_width() {
        fail("mapped tensor dtype and element width disagree");
    }
    let dimensions = slice::from_raw_parts(tensor.shape, tensor.rank as usize).to_vec();
    let byte_len = (tensor.elements as usize)
        .checked_mul(element.byte_width())
        .unwrap_or_else(|| fail("mapped tensor byte size overflow"));
    let bytes = slice::from_raw_parts(tensor.data.cast::<u8>(), byte_len).to_vec();
    let host =
        HostBuffer::new(Shape::new(element, dimensions), bytes).unwrap_or_else(|error| fail(error));
    let buffer = runtime
        .client
        .upload_to(host, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    runtime.buffers.insert(pointer as usize, buffer);
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_i64_token(value: i64) -> *mut c_void {
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    let host = HostBuffer::from_i64([1, 1], &[value]).unwrap_or_else(|error| fail(error));
    upload_host(runtime, host)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_i64_position(value: i64) -> *mut c_void {
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    let host = HostBuffer::from_i64([1], &[value]).unwrap_or_else(|error| fail(error));
    upload_host(runtime, host)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_i64_tokens(values: *mut c_void) -> *mut c_void {
    if values.is_null() {
        fail("null token list");
    }
    let count = __sev_collection_size(values);
    if count <= 0 {
        fail("cannot upload an empty token list");
    }
    if count as usize > QWEN_PREFILL_CAPACITY {
        fail(format!(
            "prompt has {count} tokens; prefill capacity is {QWEN_PREFILL_CAPACITY}"
        ));
    }
    let mut tokens = (0..count)
        .map(|index| __sev_unbox_i64(__sev_collection_get(values, index)))
        .collect::<Vec<_>>();
    tokens.resize(QWEN_PREFILL_CAPACITY, 0);
    let host = HostBuffer::from_i64([1, QWEN_PREFILL_CAPACITY as i64], &tokens)
        .unwrap_or_else(|error| fail(error));
    let mut guard = state();
    upload_host(guard.as_mut().unwrap(), host)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_prefill_tokens(values: *mut c_void) -> *mut c_void {
    if values.is_null() {
        fail("null serving token list");
    }
    let count = __sev_collection_size(values);
    if count <= 0 || count > QWEN_SERVING_PREFILL_TOKENS as i64 {
        fail(format!(
            "serving prompt has {count} tokens; expected 1..={QWEN_SERVING_PREFILL_TOKENS}"
        ));
    }
    let mut tokens = (0..count)
        .map(|index| __sev_unbox_i64(__sev_collection_get(values, index)))
        .collect::<Vec<_>>();
    tokens.resize(QWEN_SERVING_PREFILL_TOKENS, 0);
    let host = HostBuffer::from_i64([1, QWEN_SERVING_PREFILL_TOKENS as i64], &tokens)
        .unwrap_or_else(|error| fail(error));
    let mut guard = state();
    upload_host(guard.as_mut().unwrap(), host)
}

fn upload_f32(values: &[f32], dimensions: impl Into<Vec<i64>>) -> *mut c_void {
    let host = HostBuffer::from_f32(dimensions, values).unwrap_or_else(|error| fail(error));
    let mut guard = state();
    upload_host(guard.as_mut().unwrap(), host)
}

fn upload_bf16_zeros(dimensions: impl Into<Vec<i64>>, elements: usize) -> *mut c_void {
    let host = HostBuffer::new(
        Shape::new(ElementType::BF16, dimensions),
        vec![
            0;
            elements
                .checked_mul(2)
                .unwrap_or_else(|| fail("BF16 zero buffer overflow"))
        ],
    )
    .unwrap_or_else(|error| fail(error));
    let mut guard = state();
    upload_host(guard.as_mut().unwrap(), host)
}

fn qwen_rope(position_start: usize, positions: usize, sine: bool) -> *mut c_void {
    let mut values = Vec::with_capacity(positions * QWEN_HEAD_DIMENSION);
    for position in position_start..position_start + positions {
        let frequencies = (0..QWEN_HEAD_DIMENSION / 2)
            .map(|index| {
                let inverse =
                    1_000_000.0_f32.powf(-(index as f32) / (QWEN_HEAD_DIMENSION as f32 / 2.0));
                let angle = position as f32 * inverse;
                if sine {
                    angle.sin()
                } else {
                    angle.cos()
                }
            })
            .collect::<Vec<_>>();
        values.extend_from_slice(&frequencies);
        values.extend_from_slice(&frequencies);
    }
    upload_f32(
        &values,
        [1, 1, positions as i64, QWEN_HEAD_DIMENSION as i64],
    )
}

unsafe fn token_count(tokens: *mut c_void) -> usize {
    if tokens.is_null() {
        fail("null token list");
    }
    let count = __sev_collection_size(tokens);
    if count <= 0 || count as usize > QWEN_PREFILL_CAPACITY {
        fail(format!(
            "prompt token count {count} is outside prefill capacity 1..={QWEN_PREFILL_CAPACITY}"
        ));
    }
    count as usize
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_rope_cos(tokens: *mut c_void) -> *mut c_void {
    token_count(tokens);
    let mut values = Vec::with_capacity(QWEN_PREFILL_CAPACITY * 128);
    for position in 0..QWEN_PREFILL_CAPACITY {
        let frequencies = (0..64)
            .map(|index| {
                let inverse = 1_000_000.0_f32.powf(-(index as f32) / 64.0);
                (position as f32 * inverse).cos()
            })
            .collect::<Vec<_>>();
        values.extend_from_slice(&frequencies);
        values.extend_from_slice(&frequencies);
    }
    upload_f32(&values, [1, 1, QWEN_PREFILL_CAPACITY as i64, 128])
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_rope_sin(tokens: *mut c_void) -> *mut c_void {
    token_count(tokens);
    let mut values = Vec::with_capacity(QWEN_PREFILL_CAPACITY * 128);
    for position in 0..QWEN_PREFILL_CAPACITY {
        let frequencies = (0..64)
            .map(|index| {
                let inverse = 1_000_000.0_f32.powf(-(index as f32) / 64.0);
                (position as f32 * inverse).sin()
            })
            .collect::<Vec<_>>();
        values.extend_from_slice(&frequencies);
        values.extend_from_slice(&frequencies);
    }
    upload_f32(&values, [1, 1, QWEN_PREFILL_CAPACITY as i64, 128])
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_causal_mask(tokens: *mut c_void) -> *mut c_void {
    let count = token_count(tokens);
    let values = (0..QWEN_PREFILL_CAPACITY)
        .flat_map(|query| {
            (0..QWEN_PREFILL_CAPACITY).map(move |key| {
                if query < count && key <= query {
                    0.0
                } else {
                    -1.0e30
                }
            })
        })
        .collect::<Vec<_>>();
    upload_f32(
        &values,
        [
            1,
            1,
            QWEN_PREFILL_CAPACITY as i64,
            QWEN_PREFILL_CAPACITY as i64,
        ],
    )
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_prefill_rope_cos() -> *mut c_void {
    qwen_rope(0, QWEN_SERVING_PREFILL_TOKENS, false)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_prefill_rope_sin() -> *mut c_void {
    qwen_rope(0, QWEN_SERVING_PREFILL_TOKENS, true)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_prefill_causal_mask() -> *mut c_void {
    let values = (0..QWEN_SERVING_PREFILL_TOKENS)
        .flat_map(|query| {
            (0..QWEN_SERVING_PREFILL_TOKENS)
                .map(move |key| if key <= query { 0.0 } else { -1.0e30 })
        })
        .collect::<Vec<_>>();
    upload_f32(
        &values,
        [
            1,
            1,
            QWEN_SERVING_PREFILL_TOKENS as i64,
            QWEN_SERVING_PREFILL_TOKENS as i64,
        ],
    )
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_decode_rope_cos(position: i64) -> *mut c_void {
    if !(0..QWEN_SERVING_CACHE_TOKENS as i64).contains(&position) {
        fail(format!(
            "decode position {position} is outside the serving cache"
        ));
    }
    qwen_rope(position as usize, 1, false)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_decode_rope_sin(position: i64) -> *mut c_void {
    if !(0..QWEN_SERVING_CACHE_TOKENS as i64).contains(&position) {
        fail(format!(
            "decode position {position} is outside the serving cache"
        ));
    }
    qwen_rope(position as usize, 1, true)
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_decode_mask(position: i64) -> *mut c_void {
    if !(0..QWEN_SERVING_CACHE_TOKENS as i64).contains(&position) {
        fail(format!(
            "decode position {position} is outside the serving cache"
        ));
    }
    let values = (0..QWEN_SERVING_CACHE_TOKENS)
        .map(|key| {
            if key <= position as usize {
                0.0
            } else {
                -1.0e30
            }
        })
        .collect::<Vec<_>>();
    upload_f32(&values, [1, 1, 1, QWEN_SERVING_CACHE_TOKENS as i64])
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_qwen_serving_empty_cache() -> *mut c_void {
    let elements = QWEN_KV_HEADS * QWEN_SERVING_CACHE_TOKENS * QWEN_HEAD_DIMENSION;
    upload_bf16_zeros(
        [
            1,
            QWEN_KV_HEADS as i64,
            QWEN_SERVING_CACHE_TOKENS as i64,
            QWEN_HEAD_DIMENSION as i64,
        ],
        elements,
    )
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_release(tensor: *mut c_void) {
    if tensor.is_null() {
        return;
    }
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    if runtime.buffers.remove(&(tensor as usize)).is_some() {
        drop(Box::from_raw(tensor.cast::<u8>()));
    }
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_execute(
    function: u64,
    module_data: *const u8,
    module_len: usize,
    arguments: *const *mut c_void,
    argument_count: usize,
) -> *mut c_void {
    if module_data.is_null() || arguments.is_null() {
        fail("null kernel module or argument list");
    }
    let module = std::str::from_utf8(slice::from_raw_parts(module_data, module_len))
        .unwrap_or_else(|error| fail(error));
    let pointers = slice::from_raw_parts(arguments, argument_count);
    let mut guard = state();
    let runtime = guard.as_mut().unwrap();
    for &pointer in pointers {
        if pointer.is_null() {
            fail("null tensor argument");
        }
        if !runtime.buffers.contains_key(&(pointer as usize)) {
            upload_mapped_tensor(runtime, pointer);
        }
    }
    if !runtime.executables.contains_key(&function) {
        let executable = runtime
            .client
            .compile(
                &StableHloModule::from_text(module),
                &CompileOptions::default(),
            )
            .unwrap_or_else(|error| fail(error));
        runtime.executables.insert(function, executable);
    }
    let executable = runtime.executables.get(&function).unwrap();
    let inputs = pointers
        .iter()
        .map(|pointer| runtime.buffers.get(&(*pointer as usize)).unwrap())
        .collect::<Vec<_>>();
    let mut outputs = executable
        .execute(&inputs, &runtime.device)
        .unwrap_or_else(|error| fail(error));
    if outputs.len() != 1 {
        fail(format!(
            "tensor region returned {} buffers; expected one",
            outputs.len()
        ));
    }
    let handle = new_handle();
    runtime.buffers.insert(handle as usize, outputs.remove(0));
    handle
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_argmax_bf16(tensor: *mut c_void) -> i64 {
    let guard = state();
    let runtime = guard.as_ref().unwrap();
    let buffer = runtime
        .buffers
        .get(&(tensor as usize))
        .unwrap_or_else(|| fail("argmax requires an XLA output tensor"));
    let bytes = buffer.to_host_bytes().unwrap_or_else(|error| fail(error));
    bytes
        .chunks_exact(2)
        .enumerate()
        .map(|(index, bytes)| {
            let bits = u16::from_ne_bytes([bytes[0], bytes[1]]);
            (index, f32::from_bits(u32::from(bits) << 16))
        })
        .max_by(|left, right| left.1.total_cmp(&right.1))
        .map(|(index, _)| index as i64)
        .unwrap_or_else(|| fail("argmax received an empty tensor"))
}

#[no_mangle]
pub unsafe extern "C" fn __sev_xla_argmax_position_bf16(
    tensor: *mut c_void,
    tokens: *mut c_void,
) -> i64 {
    let guard = state();
    let runtime = guard.as_ref().unwrap();
    let buffer = runtime
        .buffers
        .get(&(tensor as usize))
        .unwrap_or_else(|| fail("argmax requires an XLA output tensor"));
    if buffer.shape().element_type != ElementType::BF16 {
        fail("argmax requires a BF16 tensor");
    }
    let width = buffer
        .shape()
        .dimensions
        .last()
        .copied()
        .unwrap_or_else(|| fail("argmax requires a ranked tensor"));
    if width <= 0 {
        fail("argmax received an empty final dimension");
    }
    let bytes = buffer.to_host_bytes().unwrap_or_else(|error| fail(error));
    let row_bytes = width as usize * 2;
    let position = token_count(tokens) - 1;
    let start = position
        .checked_mul(row_bytes)
        .unwrap_or_else(|| fail("argmax row offset overflow"));
    let row = bytes
        .get(start..start + row_bytes)
        .unwrap_or_else(|| fail("argmax position is outside the tensor"));
    row.chunks_exact(2)
        .enumerate()
        .map(|(index, bytes)| {
            let bits = u16::from_ne_bytes([bytes[0], bytes[1]]);
            (index, f32::from_bits(u32::from(bits) << 16))
        })
        .max_by(|left, right| left.1.total_cmp(&right.1))
        .map(|(index, _)| index as i64)
        .unwrap_or_else(|| fail("argmax received an empty tensor"))
}
