[package]
name = "severian-lowering"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
severian-coverage = { version = "0.1.0", path = "../coverage" }
severian-hir = { version = "0.1.0", path = "../hir" }
severian-mir = { version = "0.1.0", path = "../mir" }
severian-mlir = { version = "0.1.0", path = "../mlir" }
severian-platform = { version = "0.1.0", path = "../platform" }
severian-source = { version = "0.1.0", path = "../source" }
