[package]
name = "severian-mir"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
severian-artifact = { path = "../../artifact" }
severian-hir = { path = "../../frontend/hir" }
severian-universal = { path = "../../universal" }

[lib]
path = "src/lib.rs"
