use severian_source::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Identifier(String),
    Integer(String),
    Float(String),
    MeasuredNumber {
        magnitude: String,
        suffix: String,
    },
    Character(char),
    String(String),
    FormattedString(String),
    /// A punctuation operator not reserved by the language grammar. The lexer
    /// does not need a new enum variant when a package declares one.
    Operator(String),
    At,
    Ampersand,
    AmpersandEqual,
    Caret,
    CaretEqual,
    Colon,
    ColonEqual,
    QuestionEqual,
    Equal,
    Plus,
    PlusEqual,
    Minus,
    MinusEqual,
    Star,
    StarEqual,
    Slash,
    SlashEqual,
    FloorDivide,
    FloorDivideEqual,
    Percent,
    PercentEqual,
    Power,
    EqualEqual,
    NotEqual,
    Bang,
    Less,
    LessEqual,
    ShiftLeft,
    ShiftLeftEqual,
    Greater,
    GreaterEqual,
    ShiftRight,
    ShiftRightEqual,
    Arrow,
    ApproxArrow,
    Conversion,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Pipe,
    PipeEqual,
    Comma,
    Ellipsis,
    Range,
    Dot,
    Newline,
    Indent,
    Dedent,
    Eof,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
