[package]
name = "qwen_prefill_kernels"
version = "0.1.0"
edition = "2026"

[lib]
path = "../../qwen_prefill_kernels.sev"

[dependencies]
tensor = { path = "../../../../../library/tensor", version = "0.1.0" }
