#!/usr/bin/env python3
"""Measure real compiler stages for every collection; unsupported stages fail.

Use --record-only to inventory the current migration boundary without claiming
acceptance. No compiler is rebuilt; hashes and raw diagnostics are retained.
"""
import argparse
import json
from pathlib import Path

from primitives import COMPILER, ROOT, SEED, STAGES, digest, invoke, measure


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--record-only', action='store_true')
    parser.add_argument('--timeout', type=int, default=120)
    parser.add_argument('--output', type=Path, default=ROOT / 'sev_compiler/package.pkg/collection-ledger')
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    before = {str(path): digest(path) for path in (SEED, COMPILER)}
    rows = []
    subjects = sorted((ROOT / 'sev_compiler/universal/collections').glob('*.sev'))
    subjects += sorted((ROOT / 'tests/sev_compiler/fixtures/collections').glob('*.sev'))
    stages = ('seed_parse', 'seed_check', 'seed_tests', *STAGES[2:])
    for subject in subjects:
        row = measure(subject, output, args.timeout)
        directory = output / row['artifacts']
        row['stages']['seed_tests'] = invoke([SEED, 'test', subject], directory, 'seed_tests', args.timeout)
        declarations = directory / 'declarations.json'
        if declarations.exists():
            data = json.loads(declarations.read_text())
            for declaration in data:
                if subject.parent.name == 'collections' and 'universal' in subject.parts:
                    declaration['role'] = ('test' if declaration['in_test'] or declaration['kind'] in ('TestDeclaration', 'CompilerTestCase')
                                           else 'private' if declaration['private'] else 'api')
            declarations.write_text(json.dumps(data, indent=2) + '\n')
            row['api_declarations'] = sum(item['role'] == 'api' for item in data)
        rows.append(row)
        print(subject.name + ': ' + ', '.join(f"{stage}={row['stages'][stage]['status']}" for stage in stages), flush=True)
        (output / 'results.json').write_text(json.dumps({'schema_version': 1, 'compilers': before, 'files': rows}, indent=2) + '\n')
    if before != {str(path): digest(path) for path in (SEED, COMPILER)}:
        raise RuntimeError('compiler binary changed during measurement')
    summary = ['# Collection compiler measurements', '', 'Generated by `python3 tests/sev_compiler/collection_capabilities.py --record-only`.', '',
               'These are compiler stages, separate from the Python algorithm adapter.', '',
               '| File | ' + ' | '.join(stages) + ' |', '| --- | ' + ' | '.join('---' for _ in stages) + ' |']
    for row in rows:
        summary.append('| ' + row['file'] + ' | ' + ' | '.join(row['stages'][stage]['status'] for stage in stages) + ' |')
    (output / 'SUMMARY.md').write_text('\n'.join(summary) + '\n')
    if not args.record_only and any(row['stages'][stage]['status'] != 'pass' for row in rows for stage in stages):
        parser.exit(1, 'Collection compiler acceptance is incomplete; see results.json.\n')


if __name__ == '__main__':
    main()
