[package]
name = "transformer-rocm-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "transformer-rocm-example"
path = "main.sev"

[dependencies]
parallel = { path = "../../../library/parallel", version = "0.1.0" }
tensor = { path = "../../../library/tensor", version = "0.1.0" }
models = { path = "../../../library/models", version = "0.1.0" }
