[package]
name = "severian-semantic"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
severian-ast = { path = "../ast" }
severian-diagnostics = { path = "../../diagnostics" }
severian-hir = { path = "../hir" }
severian-modules = { path = "../modules" }
severian-universal = { path = "../../universal" }
severian-source = { path = "../../source" }

[lib]
path = "src/lib.rs"

[dev-dependencies]
severian-source = { path = "../../source" }
severian-bootstrap = { path = "../../bootstrap" }
severian-lexer = { path = "../lexer" }
severian-parser = { path = "../parser" }
severian-mir = { path = "../../transforms/mir" }
