use crate::{Compilation, CompileError};
use severian_hir::{Expression, Function, Instruction, ValueType};

#[derive(Debug, Clone)]
pub struct PopcornExportOptions {
    pub entry: Option<String>,
    pub leaderboard: String,
    pub gpu: Option<String>,
    pub block_size: usize,
}

impl Default for PopcornExportOptions {
    fn default() -> Self {
        Self {
            entry: None,
            leaderboard: "vectorsum_v2".into(),
            gpu: None,
            block_size: 1024,
        }
    }
}

/// Exports a recognized Severian tensor kernel as Popcorn's required single
/// Python file. The first backend is deliberately narrow: vector reduction is
/// emitted as Triton so Torch owns allocations and the active CUDA/HIP stream.
pub fn export_popcorn(
    compilation: &Compilation,
    options: &PopcornExportOptions,
) -> Result<String, CompileError> {
    if options.leaderboard != "vectorsum_v2" && options.leaderboard != "vectorsum_py" {
        return Err(CompileError::Execution(format!(
            "Popcorn leaderboard `{}` is not supported yet; the current exporter supports `vectorsum_v2`",
            options.leaderboard
        )));
    }
    if !options.block_size.is_power_of_two() || !(64..=65536).contains(&options.block_size) {
        return Err(CompileError::Execution(
            "Popcorn reduction block size must be a power of two from 64 through 65536".into(),
        ));
    }

    let candidates = compilation
        .hir
        .functions
        .iter()
        .filter(|function| is_vector_sum(function))
        .collect::<Vec<_>>();
    let function = match options.entry.as_deref() {
        Some(entry) => candidates
            .into_iter()
            .find(|function| function.name == entry)
            .ok_or_else(|| {
                CompileError::Execution(format!(
                    "entry `{entry}` is not a one-input tensor sum returning a tensor"
                ))
            })?,
        None if candidates.len() == 1 => candidates[0],
        None if candidates.is_empty() => {
            return Err(CompileError::Execution(
                "no Popcorn-compatible vector sum found; provide a function taking one Tensor, returning Tensor, and calling `tensor.sum` or `tensor.rankedSum`".into(),
            ));
        }
        None => {
            return Err(CompileError::Execution(format!(
                "multiple Popcorn-compatible vector sums found ({}); select one with `--entry NAME`",
                candidates
                    .iter()
                    .map(|function| function.name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            )));
        }
    };

    Ok(render_vectorsum(function, options))
}

fn is_vector_sum(function: &Function) -> bool {
    function.params.len() == 1
        && matches!(
            function.params[0].ty,
            ValueType::Tensor(_) | ValueType::TensorAny
        )
        && matches!(
            function.return_type,
            ValueType::Tensor(_) | ValueType::TensorAny
        )
        && instructions_contain_sum(&function.instructions)
}

fn instructions_contain_sum(instructions: &[Instruction]) -> bool {
    instructions.iter().any(|instruction| match instruction {
        Instruction::Return(Some(value))
        | Instruction::Let { value, .. }
        | Instruction::TryLet { value, .. }
        | Instruction::Evaluate(value) => expression_is_sum(value),
        Instruction::If {
            then_instructions,
            else_instructions,
            ..
        } => {
            instructions_contain_sum(then_instructions)
                || instructions_contain_sum(else_instructions)
        }
        Instruction::While { instructions, .. }
        | Instruction::For { instructions, .. }
        | Instruction::With { instructions, .. } => instructions_contain_sum(instructions),
        Instruction::Switch { arms, .. } | Instruction::ChannelSwitch { arms, .. } => arms
            .iter()
            .any(|arm| instructions_contain_sum(&arm.instructions)),
        Instruction::Assign { .. }
        | Instruction::Print(_)
        | Instruction::Assert(_)
        | Instruction::Return(None)
        | Instruction::Break
        | Instruction::Continue => false,
    })
}

fn expression_is_sum(expression: &Expression) -> bool {
    matches!(
        expression.kind(),
        Expression::Call { target, .. }
            if target.name == "tensor.sum" || target.name == "tensor.rankedSum"
    )
}

fn render_vectorsum(function: &Function, options: &PopcornExportOptions) -> String {
    let gpu = options
        .gpu
        .as_ref()
        .map(|gpu| format!("#!POPCORN gpu {gpu}\n"))
        .unwrap_or_default();
    format!(
        r#"#!POPCORN leaderboard {}
{gpu}# Generated by `sev kernel export popcorn`; edit the Severian source, then regenerate.
import torch
import triton
import triton.language as tl
from task import input_t, output_t

SEVERIAN_ENTRY = {:?}
SEVERIAN_OPERATION = "tensor.reduce_sum"

@triton.jit
def _severian_vectorsum(input_pointer, output_pointer, element_count: tl.constexpr, BLOCK_SIZE: tl.constexpr):
    program = tl.program_id(0)
    offsets = program * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    values = tl.load(input_pointer + offsets, mask=offsets < element_count, other=0.0)
    partial = tl.sum(values, axis=0)
    tl.atomic_add(output_pointer, partial)

def _custom_kernel(data: input_t) -> output_t:
    input_tensor, output_tensor = data
    element_count = input_tensor.numel()
    grid = (triton.cdiv(element_count, {}),)
    _severian_vectorsum[grid](
        input_tensor,
        output_tensor,
        element_count,
        BLOCK_SIZE={},
    )
    return output_tensor[0]

custom_kernel = torch.compile(_custom_kernel, mode="reduce-overhead")
"#,
        options.leaderboard, function.name, options.block_size, options.block_size,
    )
}
