use severian_source::Span;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    Identifier(String),
    Integer(String),
    Float(String),
    MeasuredNumber { magnitude: String, suffix: String },
    Character(char),
    String(String),
    FormattedString(String),
    At,
    Colon,
    ColonEqual,
    QuestionEqual,
    Equal,
    Plus,
    PlusEqual,
    Minus,
    MinusEqual,
    Star,
    StarEqual,
    Slash,
    SlashEqual,
    Percent,
    PercentEqual,
    Power,
    EqualEqual,
    NotEqual,
    Bang,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Arrow,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Pipe,
    Comma,
    Dot,
    Newline,
    Indent,
    Dedent,
    Eof,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
