[package]
name = "attention"
version = "0.1.0"
edition = "2026"

[lib]
path = "../../attention.sev"

[dependencies]
rope = { path = "../rope", version = "0.1.0" }
tensor = { path = "../../../../../library/tensor", version = "0.1.0" }
