[package]
name = "ranked-tensor-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "ranked-tensor-example"
path = "main.sev"

[dependencies]
tensor = { path = "../../../library/tensor", version = "0.1.0" }
