[package]
name = "distributed-learning-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "distributed-learning-example"
path = "main.sev"

[dependencies]
distributed = { path = "../../../library/distributed", version = "0.1.0" }
