[package]
name = "severian-diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
severian-ast = { version = "0.1.0", path = "../ast" }
severian-hir = { version = "0.1.0", path = "../hir" }
severian-lexer = { version = "0.1.0", path = "../lexer" }
severian-source = { version = "0.1.0", path = "../source" }

[dev-dependencies]
severian-parser = { version = "0.1.0", path = "../parser" }
