use severian_hir::{Expression, Function, Instruction, Program, ValueType};

#[test]
fn lowers_hello_to_mlir_text() {
    let program = Program {
        globals: vec![],
        classes: vec![],
        functions: vec![Function {
            name: "main".into(),
            native_symbol: None,
            decorators: vec![],
            contract: None,
            params: vec![],
            return_type: ValueType::Unit,
            instructions: vec![Instruction::Print(Expression::String(
                "hello, severian".into(),
            ))],
            tests: vec![],
        }],
    };

    assert_eq!(
        severian_lowering::lower(&program).as_str(),
        concat!(
            "module {\n",
            "  llvm.mlir.global internal constant @__sev_str_0(\"hello, severian\\00\")\n",
            "  llvm.mlir.global internal constant @__sev_fmt_int(\"%ld\\0A\\00\")\n",
            "  llvm.mlir.global internal constant @__sev_fmt_float(\"%.15g\\0A\\00\")\n",
            "  llvm.mlir.global internal constant @__sev_bool_true(\"true\\00\")\n",
            "  llvm.mlir.global internal constant @__sev_bool_false(\"false\\00\")\n",
            "  llvm.func @puts(!llvm.ptr) -> i32\n",
            "  llvm.func @printf(!llvm.ptr, ...) -> i32\n\n",
            "  llvm.func @snprintf(!llvm.ptr, i64, !llvm.ptr, ...) -> i32\n",
            "  llvm.func @malloc(i64) -> !llvm.ptr\n",
            "  llvm.func @abort()\n",
            "  llvm.func @strtod(!llvm.ptr, !llvm.ptr) -> f64\n\n",
            "  llvm.func @__sev_strlen(!llvm.ptr) -> i64\n\n",
            "  llvm.func @__sev_box_i64(i64) -> !llvm.ptr\n",
            "  llvm.func @__sev_box_f64(f64) -> !llvm.ptr\n",
            "  llvm.func @__sev_box_bool(i1) -> !llvm.ptr\n",
            "  llvm.func @__sev_box_string(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_box_collection(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_unbox_i64(!llvm.ptr) -> i64\n",
            "  llvm.func @__sev_unbox_f64(!llvm.ptr) -> f64\n",
            "  llvm.func @__sev_unbox_bool(!llvm.ptr) -> i1\n",
            "  llvm.func @__sev_unbox_string(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_unbox_ptr(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_value_add(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_value_sub(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_value_mul(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_value_div(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_value_float(!llvm.ptr) -> f64\n",
            "  llvm.func @__sev_value_string(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_string_concat(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_string_equal(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_value_equal(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_value_less(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_collection_new(i64) -> !llvm.ptr\n",
            "  llvm.func @__sev_collection_push(!llvm.ptr, !llvm.ptr)\n",
            "  llvm.func @__sev_collection_get(!llvm.ptr, i64) -> !llvm.ptr\n",
            "  llvm.func @__sev_collection_set(!llvm.ptr, i64, !llvm.ptr)\n",
            "  llvm.func @__sev_collection_size(!llvm.ptr) -> i64\n",
            "  llvm.func @__sev_collection_equal(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_collection_reversed(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_set_contains(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_map_new() -> !llvm.ptr\n",
            "  llvm.func @__sev_map_insert(!llvm.ptr, !llvm.ptr, !llvm.ptr)\n",
            "  llvm.func @__sev_map_get(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_map_size(!llvm.ptr) -> i64\n",
            "  llvm.func @__sev_map_key_at(!llvm.ptr, i64) -> !llvm.ptr\n",
            "  llvm.func @__sev_map_value_at(!llvm.ptr, i64) -> !llvm.ptr\n",
            "  llvm.func @__sev_print_value(!llvm.ptr)\n",
            "  llvm.func @__sev_print_collection(!llvm.ptr)\n\n",
            "  llvm.func @__sev_print_value_inline(!llvm.ptr)\n",
            "  llvm.func @__sev_print_space()\n",
            "  llvm.func @__sev_print_newline()\n",
            "  llvm.func @__sev_object_new(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_object_set(!llvm.ptr, !llvm.ptr, !llvm.ptr)\n",
            "  llvm.func @__sev_object_get(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_object_is(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_matrix_new(i64, i64, f64) -> !llvm.ptr\n",
            "  llvm.func @__sev_matrix_shape(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_matrix_multiply(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_matrix_scale(!llvm.ptr, f64) -> !llvm.ptr\n",
            "  llvm.func @__sev_matrix_equal(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_matrix_print(!llvm.ptr)\n",
            "  llvm.func @__sev_dispatch_draw(!llvm.ptr)\n\n",
            "  llvm.func @__sev_variant_new(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_variant_is(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_variant_field(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_print_variant(!llvm.ptr)\n\n",
            "  llvm.func @__sev_builtin_read(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_builtin_http_get(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_builtin_int_parse(!llvm.ptr) -> !llvm.ptr\n",
            "  llvm.func @__sev_builtin_file_write(!llvm.ptr, !llvm.ptr) -> !llvm.ptr\n\n",
            "  llvm.func @__sev_regex_matches(!llvm.ptr, !llvm.ptr) -> i1\n",
            "  llvm.func @__sev_task_await_unit(!llvm.ptr)\n\n",
            "  llvm.func @llvm.sqrt.f64(f64) -> f64\n\n",
            "  llvm.func @main() -> i32 {\n",
            "    %v0 = llvm.mlir.addressof @__sev_str_0 : !llvm.ptr\n",
            "    %v1 = llvm.call @puts(%v0) : (!llvm.ptr) -> i32\n",
            "    %v2 = llvm.mlir.constant(0 : i32) : i32\n",
            "    llvm.return %v2 : i32\n",
            "  }\n",
            "}\n",
        )
    );
}
