#!/usr/bin/env python3
"""Generate the native example status table from the mandatory acceptance test."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "docs" / "examples"
OUTPUT = ROOT / "docs" / "NATIVE_STATUS.md"


def inventory() -> list[tuple[str, int, int]]:
    rows: list[tuple[str, int, int]] = []
    for directory in sorted(path for path in EXAMPLES.iterdir() if path.is_dir()):
        sources = sorted(directory.rglob("*.sev"))
        invalid = sum(path.name == "invalid.sev" for path in sources)
        rows.append((directory.name, len(sources) - invalid, invalid))
    return rows


def render(rows: list[tuple[str, int, int]]) -> str:
    valid_total = sum(valid for _, valid, _ in rows)
    invalid_total = sum(invalid for _, _, invalid in rows)
    lines = [
        "# Native acceptance status",
        "",
        "<!-- Generated by tools/example_status.py. Do not edit by hand. -->",
        "",
        "This table is generated only after the exhaustive native acceptance test passes. "
        "For every valid source, `compile_path` completes parsing, semantic type checking, "
        "ownership checking, optimization, and MLIR emission; the native backend then links "
        "and runs an executable whose stdout must exactly match its fixture. Expected-invalid "
        "sources must be rejected with their checked diagnostic fixture.",
        "",
        f"Current inventory: **{valid_total} native programs** and "
        f"**{invalid_total} expected diagnostics**.",
        "",
        "| Example group | Scope | Programs | Diagnostics | Parse | Type | Ownership | MLIR | Link | Run | Tested |",
        "|---|---|---:|---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|",
    ]
    for name, valid, invalid in rows:
        status = "✓" if valid else "—"
        number = int(name.split("-", 1)[0]) if name[0].isdigit() else None
        if number is not None and number <= 16:
            scope = "supported core"
        elif number == 26:
            scope = "conformance corpus"
        elif name == "bugs":
            scope = "diagnostic regression"
        else:
            scope = "experimental"
        lines.append(
            f"| `{name}` | {scope} | {valid} | {invalid} | {status} | {status} | {status} | "
            f"{status} | {status} | {status} | {status} |"
        )
    lines.extend(
        [
            "",
            "`Tested` means the source is covered by the exhaustive Rust acceptance test and "
            "has an exact native stdout fixture; it does not imply every source declares an "
            "`@test` function. Diagnostic fixtures are counted separately and are exercised "
            "by the same acceptance test.",
            "",
            "Scope is deliberately narrower than execution coverage: `supported core` is the "
            "ordinary language baseline, while `experimental` examples exercise prototypes "
            "without promising a stable public API.",
            "",
            "This is the host-native CPU baseline. A host pass for a GPU, database, web, model, "
            "or operating-system example does not claim production readiness for the external "
            "service, accelerator, or freestanding target it models.",
            "",
            "Verify the table and all underlying evidence with:",
            "",
            "```sh",
            "python3 tools/example_status.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def verify_native_acceptance() -> None:
    subprocess.run(
        ["cargo", "test", "-p", "severian-driver", "--test", "native_example_output"],
        cwd=ROOT,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify acceptance and the checked-in table")
    mode.add_argument("--write", action="store_true", help="verify acceptance and update the table")
    parser.add_argument(
        "--inventory-only",
        action="store_true",
        help="do not execute acceptance (useful only while editing the generator)",
    )
    args = parser.parse_args()

    if not args.inventory_only:
        verify_native_acceptance()
    generated = render(inventory())
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            print(f"error: {OUTPUT.relative_to(ROOT)} is stale; run with --write", file=sys.stderr)
            return 1
        print(f"verified {OUTPUT.relative_to(ROOT)}")
    elif args.write:
        OUTPUT.write_text(generated)
        print(f"updated {OUTPUT.relative_to(ROOT)}")
    else:
        print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
