[package]
name = "inference-node-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "inference-node-example"
path = "main.sev"

[dependencies]
models = { path = "../../../library/models", version = "0.1.0" }
network = { path = "../../../library/network", version = "0.1.0" }
orchestrator = { path = "../../../library/orchestrator", version = "0.1.0" }
tensor = { path = "../../../library/tensor", version = "0.1.0" }
