[package]
name = "transformer-container-example"
version = "0.1.0"
edition = "2026"

[[bin]]
name = "transformer-container-example"
path = "main.sev"

[dependencies]
container = { path = "../../../library/container", version = "0.1.0" }
model = { path = "../../../library/model", version = "0.1.0" }
"model.neuralnet" = { path = "../../../library/model/neuralnet", version = "0.1.0" }
